[package]
name = "zk-settlement"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
secp256k1 = { version = "0.24.0", features = ["rand"] }
rand = "0.8.5"
num-bigint = "0.4"
num-traits = "0.2"
